### ISSUE TITLE
Mailchimp support

### ISSUE THREAD

**Issue by kbariotis** [eddywashere/node-prelaunch#1]
Hey,  great piece.

What about adding Mailchimp support as a configurable option. A lot of people use it on their landing pages.

I will be more than happy to contribute. Let me know. 

Thank you

**Comment by eddywashere** [comment]
Hey @kbariotis thanks for submitting an issue. Apologies for the delayed response.

First off some disclosure, I work for Mailgun.

Here are my thoughts: 
- mailchimp is great for mailing lists, but I wanted to be able to use something once an app has launched
  - right now confirmed users are in the database my app uses
  - email templates are checked in
  - methods are available for my app to use when it's launched and needs transactional sending capabilities (ex: send password reset codes when app is launched)
- one could easily add mailchimp to any app/site, so I don't think keeping an example app like this with mailchimp support is very useful.
- the constructive feedback I've received online usually falls into 2 categories
  - 1) "this app is too complicated, I usually use mailchimp for stuff like this" (not my target audience)
  - 2) "I've always wanted a DIY sign up service like this" (my target audience)

All that said, I think adding mailchimp support to this repo would be out of scope for the purpose of this project. 

Again, thanks for the submitting the issue. I went ahead and updated the project readme to include a contributing section to help set expectations for other contributors.
